[chg] Use pybuilder:deb9-py3.11
to fix:

[PYI-2867:ERROR] Module object for struct is NULL!
Traceback (most recent call last):
  File "struct.py", line 13, in <module>
ModuleNotFoundError: No module named '_struct'